language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
before_install:
- bundle update mimemagic
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: YNx75giKEksz809J1PcRpbdhLZqdBSn73i9L5mu7C+AvVHWaNThlZoTxq+eIVVlovc/Ye3ULzFXAgboMDGgfuSLeLWlr2qG+NvSPbXcYFeEdrukudrZWbFvzzFADfdDhfyUawxSoaSbaGTlE7iDvsim8QuD3kdUB2gYZMONOK6Jh9WoHbkNUo5kgzEnZvH/HxWkLcXC9vQheOKwNot/tR11AHpWMRGvmzNcmal8UWC9eNhiQkVeisD7L7ZE1wxlpxn+8I4IeabziQpj/ohDrTY7BZGSxMKBX7NBms3PJWDiRIzAyVxK1pslIbEN7KlmQgBmAsMcWsINfNoF7jMB9RmW2NjESycQh5umJV4jyc52M2VWRhbeNkKaqjxDZM2ZaZlgFmlOFs5DnqclqwmmunsaLWen1SQnAcMmIPMYWc7QSzDGmzp1rsc/yOsefst6L/44fsHgK2FqDfOvSHFK7LjGT5ZGTrBG7UJ+J/4z2g9a2cwMyzrBz8kvbFatOOfFihdFHG5i9aBU9cp3sL4UFTL8Z7whVhaeRyDcg/TinrjsLXJ+3DUl3ikMwZz1PmtsDUXyHRrad1Bv3nrKVMSOJbcsEW+f1UN9V8SYqr5UxAm9MQt7zUDHl8rvyJfhtE4Ct0pDIcChRimO31as9nhszXvOrVRsaRLd6gF3ouBEwzlA=
  app: young-island-83007
  on:
    repo: harrison-blake/viewing_party
  run: rails db:migrate
